name: MobPlugin
main: me.toomuchzelda.mobplugin.MobPlugin
version: 1.0.1
api-version: 1.17
commands:
 mobgrabber:
  description: MobGrabber stuff
  aliases: mbg
  usage: /<command> help

permissions:
    mobgrabber.*:
        description: Gives access to all mobgrabber
        children:
            mobgrabber.debug: true
            mobgrabber.give: true
    mobgrabber.give:
        description: Use /mbc give
        default: true
    mobgrabber.debug:
        description: Use /mbc debug
        default: true