name: MobPlugin
main: me.toomuchzelda.mobplugin.MobPlugin
version: 2
api-version: 1.17
commands:
 mobcontroller:
  description: MobGrabber stuff
  aliases: mbc
  usage: /<command> [debug]

permissions:
    mobgrabber.*:
        description: Gives access to all mobgrabber
        children:
            mobgrabber.debug: true
            mobgrabber.give: true
    mobgrabber.give:
        description: Use /mbc give
        default: true
    mobgrabber.debug:
        description: Use /mbc debug
        default: true